### ISSUE TITLE
Make optional dependencies

### ISSUE THREAD

**Issue by andvikt** [Toloka/toloka-kit#66]
Some of dependencies could be optional:

'pandas',
'plotly',
'ipyplot',
'jupyter-dash',

May be more.
Those are huge packages and not needed for everyone. You could wrap it with "extras_require" in setup and dummy imports in code like 
```python
try:
  import pandas as pd
except ImportError:
  pd = None
```

**Comment by alexdrydew** [comment]
Hello! Thank you for the provided feedback!

We acknowledge this problem; it is one of the top priority tasks for us. Currently, we are in the process of designing a solution that can address the issue. The problem is to create a friendly and intuitive separation of the package that won't be too confusing to use. The popular idea is to make streaming and metrics optional subpackages which will let us get rid of `boto3`, `jupyter-dash`, `kazoo`, `plotly` and `ipyplot` dependencies in the core version of toloka-kit.

We will try to see what we can do and reach out to you when we will have some progress.
